Repository IIIF/api, pull requests merged in 2019-05, with the labels that each got.

#1809 Image info response must include all qualities beyond default
  source/api/image/3.0/compliance.md
  source/api/image/3.0/index.md
Labels: Ready-for-TRC, normative

#1815 Annotation Page processing
  source/api/presentation/3.0/index.md
Labels: Approved-by-TRC, normative

#1814 ^pct:n clarification and canonical values for upscaling
  source/api/image/3.0/index.md
Labels: Ready-for-TRC, normative

#1816 Image preferredFormats
  source/_includes/links.md
  source/api/image/3.0/index.md
  source/api/image/3/context.json
Labels: Approved-by-TRC, normative

#1799 Mark w,h syntax required at level1
  source/api/image/3.0/compliance.md
Labels: Approved-by-TRC, normative

#1841 Fix label examples in 4.2 and 5.1, fix spacing in other examples
  source/api/presentation/3.0/index.md
Labels: editorial
